### ISSUE TITLE
PieChart

### ISSUE THREAD

**Issue by 7KiLL** [7KiLL/blockchain-front-demo#7]
Удалить PieChart в дешборде и сделать просто список со счетами. Также ссылаться на NGRX, но убрать диаграмму. 
`src/app/modules/dashboard/containers/home-container`

**Comment by 7KiLL** [comment]
> c. In the dash board you will need  to present to two amounts, the total amount and to show that the money were split to the various parties. NOT through a wheel but independently. These parties should be the shops where the products were bought from, the shopping center, us and the Creative agency. The total of course should be what the consumer paid

> What about (C), I have to just remove Pie Chart and add a listings of shops, shopping center, us and agency? I quite don't understand the point of removing pie chart 

> yes

**Comment by iamorest** [comment]
@7KiLL 

> shops where the products were bought from, the shopping center, us and the Creative agency
а что из них Creative agency, Shopping center and us?

или не важно, и просто перенести все из пайчарта в текст?

**Comment by 7KiLL** [comment]
> @7KiLL 
> 
> 
> 
> > shops where the products were bought from, the shopping center, us and the Creative agency
> 
> 
> 
> а что из них Creative agency, Shopping center and us?
> 
> или не важно, и просто перенести все из пайчарта в текст?

Просто перенеси, а там походу разберёшься что к чему. Какой кошелек к чему относится.
