### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by 7KiLL** [7KiLL/blockchain-front-demo#9]
>good job. One small correction. On the dashboard on the right write somewhere the total amount and place the amounts in vertical not just after the recipients 

>aaahhh and replace the word wallet with Distribution of Receivables

>....and if possible write the product descriptions in English :-) 

>in both the front and dashboard

**Comment by iamorest** [comment]
@7KiLL two 'distribution' words side by side don't look nice
